# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kevashcraft/radiograms-io
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: radiograms-io.kevapps.com
      paths: ['']
  tls:
    - secretName: radiograms-io-kevapps-tls
      hosts:
        - radiograms-io.kevapps.com

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
